// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylefihvjlyzabhvgdnoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsZWZpaHZqbHl6YWJodmdkbm9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTY5MTMsImV4cCI6MjA3MTk3MjkxM30.zoZbhisdfXT_Wzzs2BMiLfX4XrSq6napkbDK8Zlg9bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});